### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ksolan** [jupyter/configurable-http-proxy#25]
I'm getting an exception when I try to run a freshly installed configurable-http-proxy:
```
$ sudo apt-get install npm nodejs-legacy
$ sudo npm install -g configurable-http-proxy
$ configurable-http-proxy

util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:555:43)
    at Object.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
```
It was working fine on a machine I installed it on a couple weeks ago, but I reinstalled it today (on this machine and another) and found that it was broken. The working and broken versions were the same (0.2.1). Maybe some dependency in the chain got upgraded and broke things?

Here are the installed dependencies of the broken version:
```
├── strftime@0.8.4
├── commander@2.8.0 (graceful-readlink@1.0.1)
├── http-proxy@1.6.2 (eventemitter3@1.0.1)
└── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, colors@0.6.2, async@0.2.10, pkginfo@0.3.0)
```
Unfortunately I didn't get a snapshot of the dependencies of the working version before I reinstalled and broke it.

My node version:
```
{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.10.0',
  uv: '0.10.23',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1f',
  npm: '1.3.10' }
```
If somebody with a working install could compare this against their installed dependencies/versions, I can try to pinpoint what broke.

**Comment by ksolan** [comment]
Poked around Github a bit...looks like a dependency of node-http-proxy (https://github.com/primus/eventemitter3) was updated to v1 today. Apparently it doesn't play nice with node-http-proxy v1.6.2, which ultimately breaks configurable-http-proxy.

Downgraded eventemitter3 to 0.1.6 and things are working once more. My dependencies:
```
├── strftime@0.8.4
├── commander@2.8.0 (graceful-readlink@1.0.1)
├── http-proxy@1.6.2 (eventemitter3@0.1.6)
└── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, colors@0.6.2, async@0.2.10, pkginfo@0.3.0)
```
Not sure how this should be handled since the problem is outside this project, but anybody who installs configurable-http-proxy (or JupyterHub) from today on won't be able to use it without manually tweaking this sub-dependency.

**Comment by basnijholt** [comment]
I'm having the same problem https://github.com/jupyter/jupyterhub/issues/237

I uninstalled configurable-http-proxy, installed eventemitter3@0.1.6, then http-proxy@1.6.2, and finally configurable-http-proxy, but still it's not working.
