### ISSUE TITLE
Upgrading to HTTPS automatically.

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/configurable-http-proxy#30]
For the sake of JupyterHub, it would be really convenient if on simple deployments using certs if there was a way to forward port 80 to 443. Perhaps this could be an extra flag that runs a simple redirect server alongside the other services?

```node
var http = require('http');
http.createServer(function (req, res) {
    res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
    res.end();
}).listen(80);
```

Not sure how best to expose this as an option or if you would want this in here.

**Comment by minrk** [comment]
Great idea. It's always bugged me that we can't do this with tornado.

**Comment by rgbkrk** [comment]
Ok, cool. I'll draft a PR.
