### ISSUE TITLE
Add a Swagger (or similar?) spec for the REST API

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/configurable-http-proxy#39]
This would allow creation of alternative proxying setups (See https://github.com/jupyter/jupyterhub/issues/109 for a possible use case) that 'conform to the spec'.

**Comment by yuvipanda** [comment]
I will work on this if there is interest in accepting this as a PR into the repo.

**Comment by minrk** [comment]
:100: great idea.

**Comment by yuvipanda** [comment]
Excellent. I'll add a PR sometime this week!
