### ISSUE TITLE
nodejs assertion leads to proxy death

### ISSUE THREAD

**Issue by parente** [jupyter/configurable-http-proxy#41]
In our jupyter.cloudet.xyz deploy, we occassionally get the following crash that ultimately leads to proxy death. This is using the latest jupyter/configurable-http-proxy docker image from Docker Hub:

```
17:06:26.765 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:9999
17:06:26.770 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
21:47:17.939 - error: [ConfigProxy] Proxy error:  code=ECONNRESET
21:47:17.942 - error: [ConfigProxy] 503 GET /spawn/user/ApCsqQZgteFU/notebooks/widgets/examples/urth-pyspark-streaming.ipynb
00:40:17.180 - error: [ConfigProxy] Proxy error:  code=ECONNRESET
00:40:17.181 - error: [ConfigProxy] 503 GET /spawn/user/ApCsqQZgteFU/notebooks/widgets/examples/urth-pyspark-streaming.ipynb
00:40:17.183 - error: [ConfigProxy] Proxy error:  code=ECONNRESET
00:40:17.183 - error: [ConfigProxy] 503 GET /user/ApCsqQZgteFU/notebooks/widgets/examples/urth-pyspark-streaming.ipynb
00:40:17.405 - error: [ConfigProxy] Proxy error:  code=ECONNRESET
00:40:17.405 - error: [ConfigProxy] 503 GET /spawn/user/ApCsqQZgteFU/notebooks/index.ipynb

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:474:7)
    at emitNone (events.js:72:20)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:529:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by parente** [comment]
Bug appears to be in nodejs (https://github.com/nodejs/node/issues/2639) and is fixed as of node 4.1.2.

**Comment by parente** [comment]
The Dockerfile is pointing to `node:latest` so the unrelated PR merge yesterday triggered a rebuild of the image on Docker Hub. I'll try running that image for a while on our tmpnb cluster to see if things are fixed. (I have no other way of reproducing.) Will report back.

On a side note: we might want to consider pinning the `FROM node:latest` tag to a more explicit version like 5-slim or 5.1-slim to avoid future surprises on automatic build. (The slim version shaves about 50 MB off the image size too.)

**Comment by rgbkrk** [comment]
5-slim seems fine to me

**Comment by minrk** [comment]
AOK with 5-slim

**Comment by parente** [comment]
Sorry guys. Totally forgot about this. 

Happy to report that node 4.1.2 bug fix also solved the original problem.
