### ISSUE TITLE
route deletion leads to default route unavailability

### ISSUE THREAD

**Issue by peperAnne** [jupyter/configurable-http-proxy#45]
I'm managing configurable-http-proxy in php.

Adding route is working fine :

```php
$s = curl_init();
curl_setopt($s, CURLOPT_POST, 1);
curl_setopt($s, CURLOPT_URL,"http://localhost:81/api/routes/test");
curl_setopt($s, CURLOPT_POSTFIELDS,'{"target":"http://10.10.10.10:1234"}');
$x = curl_exec($s);
curl_close($s);
```

And everything is working fine after adding route

But deleting a route cause the default route to be deleted too :

```php
$s = curl_init();
curl_setopt($s, CURLOPT_URL,"http://localhost:81/api/routes/test");
curl_setopt($s, CURLOPT_CUSTOMREQUEST, "DELETE");
$x = curl_exec($s);
curl_close($s);
```

I'm sure I'm wrong somewhere, but I can't find where.

Thanks

**Comment by minrk** [comment]
How are you starting the proxy?

**Comment by minrk** [comment]
Should be fixed by #46

**Comment by peperAnne** [comment]
That's greet. Thank you for the #46.

For information, i'm starting the proxy with

```php
configurable-http-proxy --default-target=http://localhost:8080 --port=80
```

**Comment by peperAnne** [comment]
It works fine now.
Thanks !

**Comment by minrk** [comment]
@peperAnne thanks for confirming!
